/* ============================================================
   Arena Archers — game data
   Characters and levels live here so they're easy to extend.
   Each stat is on a 1–10 scale and gets mapped to real values
   in game.js. `locked` drives the lock UI; flip to false (or
   unlock via progress) to enable.
   ============================================================ */

const CHARACTERS = [
  {
    id: "robin",
    name: "Robin",
    role: "All-Rounder",
    color: "#4fc3ff",
    emoji: "🏹",
    desc: "Balanced archer with no glaring weakness. A great place to start.",
    stats: { speed: 6, damage: 6, fireRate: 6, health: 6 },
    locked: false,
  },
  {
    id: "swift",
    name: "Swift",
    role: "Skirmisher",
    color: "#7ef0a2",
    emoji: "💨",
    desc: "Lightning-fast and rapid-firing, but fragile. Hit and run.",
    stats: { speed: 9, damage: 4, fireRate: 9, health: 4 },
    locked: false,
  },
  {
    id: "bruin",
    name: "Bruin",
    role: "Bulwark",
    color: "#ffce54",
    emoji: "🛡️",
    desc: "A tanky bruiser. Slow arrows, but devastating and hard to kill.",
    stats: { speed: 4, damage: 9, fireRate: 4, health: 9 },
    locked: false,
  },
  {
    id: "ranger",
    name: "Ranger",
    role: "Marksman",
    color: "#c89bff",
    emoji: "🎯",
    desc: "Precision sniper. Big charged shots reward careful aiming.",
    stats: { speed: 5, damage: 8, fireRate: 5, health: 5 },
    locked: false,
  },
  {
    id: "ember",
    name: "Ember",
    role: "Glass Cannon",
    color: "#ff7a45",
    emoji: "🔥",
    desc: "Hits like a truck and moves fast — but folds under pressure.",
    stats: { speed: 7, damage: 9, fireRate: 6, health: 3 },
    locked: true,
    unlockHint: "Win 1 match",
  },
  {
    id: "frost",
    name: "Frost",
    role: "Controller",
    color: "#62d8ff",
    emoji: "❄️",
    desc: "Steady, durable, and relentless with a high rate of fire.",
    stats: { speed: 5, damage: 5, fireRate: 8, health: 7 },
    locked: true,
    unlockHint: "Win 3 matches",
  },
  {
    id: "shade",
    name: "Shade",
    role: "Assassin",
    color: "#9aa4bd",
    emoji: "🗡️",
    desc: "Deadly up close. The longest dash and a vicious melee slash.",
    stats: { speed: 8, damage: 7, fireRate: 7, health: 5 },
    locked: true,
    unlockHint: "Win 5 matches",
  },
  {
    id: "titan",
    name: "Titan",
    role: "Juggernaut",
    color: "#ff5d73",
    emoji: "⚡",
    desc: "The ultimate fighter — strong in every stat. Hard to earn.",
    stats: { speed: 7, damage: 8, fireRate: 7, health: 9 },
    locked: true,
    unlockHint: "Win 8 matches",
  },
];

const LEVELS = [
  {
    id: "grove",
    name: "Sunlit Grove",
    desc: "Open arena, scattered trees for cover.",
    floor: "#1d3326",
    grid: "#2a4a36",
    accent: "#3e6b48",
    locked: false,
    obstacles: [
      { x: 240, y: 160, r: 34 },
      { x: 700, y: 200, r: 30 },
      { x: 480, y: 420, r: 40 },
      { x: 760, y: 460, r: 26 },
      { x: 180, y: 440, r: 28 },
    ],
  },
  {
    id: "dunes",
    name: "Desert Dunes",
    desc: "Wide-open sand. Nowhere to hide.",
    floor: "#3a2f1c",
    grid: "#4a3d24",
    accent: "#6b5630",
    locked: false,
    obstacles: [
      { x: 480, y: 300, r: 46 },
      { x: 200, y: 200, r: 24 },
      { x: 760, y: 400, r: 24 },
    ],
  },
  {
    id: "ruins",
    name: "Stone Ruins",
    desc: "Crumbling pillars create tight sightlines.",
    floor: "#23262e",
    grid: "#33373f",
    accent: "#474c57",
    locked: false,
    obstacles: [
      { x: 200, y: 150, r: 26 }, { x: 200, y: 450, r: 26 },
      { x: 760, y: 150, r: 26 }, { x: 760, y: 450, r: 26 },
      { x: 480, y: 150, r: 26 }, { x: 480, y: 450, r: 26 },
      { x: 340, y: 300, r: 26 }, { x: 620, y: 300, r: 26 },
    ],
  },
  {
    id: "frostpeak",
    name: "Frostpeak",
    desc: "Icy plateau ringed with boulders.",
    floor: "#1b2a3a",
    grid: "#26415c",
    accent: "#35597e",
    locked: true,
    unlockHint: "Win 2 matches",
    obstacles: [
      { x: 300, y: 120, r: 30 }, { x: 660, y: 120, r: 30 },
      { x: 480, y: 320, r: 50 },
      { x: 300, y: 500, r: 30 }, { x: 660, y: 500, r: 30 },
    ],
  },
  {
    id: "volcano",
    name: "Volcano Rim",
    desc: "Fight on the edge. Heavy cover, hot tempers.",
    floor: "#2e1414",
    grid: "#451d1d",
    accent: "#6e2a2a",
    locked: true,
    unlockHint: "Win 4 matches",
    obstacles: [
      { x: 160, y: 300, r: 36 }, { x: 800, y: 300, r: 36 },
      { x: 480, y: 140, r: 32 }, { x: 480, y: 460, r: 32 },
      { x: 320, y: 300, r: 22 }, { x: 640, y: 300, r: 22 },
    ],
  },
  {
    id: "void",
    name: "The Void Arena",
    desc: "A floating platform in nowhere. Final test.",
    floor: "#14101f",
    grid: "#241a3a",
    accent: "#3a2a5e",
    locked: true,
    unlockHint: "Win 6 matches",
    obstacles: [
      { x: 480, y: 300, r: 30 },
      { x: 300, y: 200, r: 22 }, { x: 660, y: 200, r: 22 },
      { x: 300, y: 400, r: 22 }, { x: 660, y: 400, r: 22 },
    ],
  },
];
